// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DashboardHeader: typeof import('./src/components/dashboard/DashboardHeader.vue')['default']
    MainCard: typeof import('./src/components/dashboard/MainCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionsList: typeof import('./src/components/dashboard/TransactionsList.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMain: typeof import('vuetify/lib')['VMain']
  }
}

export {}
